

import { PrismaClient } from "../app/generated/prisma/client.js"
import { Pool } from "pg"
import { PrismaPg } from "@prisma/adapter-pg"

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL environment variable is not set. Check your .env file.")
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })
/**
 * Seed data - 50 sales transactions
 * No CSV dependency - all data is hardcoded here
 */
const salesData = [
  { transactionId: 1, date: '2023-03-23', customerId: 'CUST-40823', customerName: 'Neha Khan', phoneNumber: '9720639364', gender: 'Male', age: 21, customerRegion: 'East', customerType: 'Returning', productId: 'PROD-8721', productName: 'Herbal Face Wash', brand: 'SilkSkin', productCategory: 'Beauty', tags: ['organic', 'skincare'], quantity: 5, pricePerUnit: 4268, discountPercentage: 12, totalAmount: 21340, finalAmount: 18779.2, paymentMethod: 'UPI', orderStatus: 'Cancelled', deliveryType: 'Standard', storeId: 'ST-015', storeLocation: 'Ahmedabad', salespersonId: 'EMP-7554', employeeName: 'Harsh Agarwal' },
  { transactionId: 2, date: '2021-01-30', customerId: 'CUST-79592', customerName: 'Prerna Mehta', phoneNumber: '9159953102', gender: 'Male', age: 19, customerRegion: 'Central', customerType: 'Returning', productId: 'PROD-5451', productName: 'USB-C Charger', brand: 'TechPulse', productCategory: 'Electronics', tags: ['portable', 'wireless'], quantity: 5, pricePerUnit: 4626, discountPercentage: 28, totalAmount: 23130, finalAmount: 16653.6, paymentMethod: 'UPI', orderStatus: 'Returned', deliveryType: 'Express', storeId: 'ST-006', storeLocation: 'Chennai', salespersonId: 'EMP-1890', employeeName: 'Ankit Tiwari' },
  { transactionId: 3, date: '2022-08-23', customerId: 'CUST-53317', customerName: 'Arjun Das', phoneNumber: '9624084493', gender: 'Male', age: 24, customerRegion: 'North', customerType: 'Returning', productId: 'PROD-8448', productName: 'Gaming Mouse', brand: 'CyberCore', productCategory: 'Electronics', tags: ['portable', 'gadgets', 'wireless'], quantity: 3, pricePerUnit: 575, discountPercentage: 43, totalAmount: 1725, finalAmount: 983.25, paymentMethod: 'Credit Card', orderStatus: 'Completed', deliveryType: 'Store Pickup', storeId: 'ST-038', storeLocation: 'Pune', salespersonId: 'EMP-5981', employeeName: 'Khushi Agarwal' },
  { transactionId: 4, date: '2021-02-03', customerId: 'CUST-13864', customerName: 'Zoya Joshi', phoneNumber: '9396223918', gender: 'Male', age: 60, customerRegion: 'South', customerType: 'Returning', productId: 'PROD-5915', productName: 'Slim Fit Jeans', brand: 'UrbanWeave', productCategory: 'Clothing', tags: ['casual', 'fashion', 'unisex'], quantity: 1, pricePerUnit: 2538, discountPercentage: 26, totalAmount: 2538, finalAmount: 1878.12, paymentMethod: 'Debit Card', orderStatus: 'Returned', deliveryType: 'Store Pickup', storeId: 'ST-048', storeLocation: 'Lucknow', salespersonId: 'EMP-4266', employeeName: 'Ashmi Jain' },
  { transactionId: 5, date: '2021-03-31', customerId: 'CUST-98319', customerName: 'Anjali Yadav', phoneNumber: '9669733171', gender: 'Male', age: 25, customerRegion: 'North', customerType: 'Loyal', productId: 'PROD-5961', productName: 'Herbal Face Wash', brand: 'SilkSkin', productCategory: 'Beauty', tags: ['skincare', 'makeup', 'organic'], quantity: 4, pricePerUnit: 4890, discountPercentage: 44, totalAmount: 19560, finalAmount: 10953.6, paymentMethod: 'UPI', orderStatus: 'Completed', deliveryType: 'Express', storeId: 'ST-014', storeLocation: 'Mumbai', salespersonId: 'EMP-9553', employeeName: 'Ram Chaudhry' },
  { transactionId: 6, date: '2021-08-31', customerId: 'CUST-53321', customerName: 'Suresh Iyer', phoneNumber: '9657125783', gender: 'Female', age: 55, customerRegion: 'North', customerType: 'Returning', productId: 'PROD-9434', productName: 'Cotton T-Shirt', brand: 'StreetLayer', productCategory: 'Clothing', tags: ['unisex', 'fashion', 'cotton'], quantity: 4, pricePerUnit: 1103, discountPercentage: 12, totalAmount: 4412, finalAmount: 3882.56, paymentMethod: 'UPI', orderStatus: 'Pending', deliveryType: 'Express', storeId: 'ST-039', storeLocation: 'Mumbai', salespersonId: 'EMP-3759', employeeName: 'Ashmi Jain' },
  { transactionId: 7, date: '2021-04-28', customerId: 'CUST-76213', customerName: 'Ritika Chopra', phoneNumber: '9100671247', gender: 'Male', age: 42, customerRegion: 'West', customerType: 'New', productId: 'PROD-2486', productName: 'Bluetooth Speaker', brand: 'VoltEdge', productCategory: 'Electronics', tags: ['smart', 'gadgets', 'portable', 'wireless'], quantity: 1, pricePerUnit: 4981, discountPercentage: 17, totalAmount: 4981, finalAmount: 4134.23, paymentMethod: 'Credit Card', orderStatus: 'Returned', deliveryType: 'Store Pickup', storeId: 'ST-006', storeLocation: 'Jaipur', salespersonId: 'EMP-6815', employeeName: 'Khushi Agarwal' },
  { transactionId: 8, date: '2021-07-12', customerId: 'CUST-10839', customerName: 'Mahesh Mehta', phoneNumber: '9965297269', gender: 'Male', age: 47, customerRegion: 'East', customerType: 'New', productId: 'PROD-9154', productName: 'Hooded Sweatshirt', brand: 'ComfortLine', productCategory: 'Clothing', tags: ['fashion', 'casual', 'unisex'], quantity: 1, pricePerUnit: 671, discountPercentage: 45, totalAmount: 671, finalAmount: 369.05, paymentMethod: 'Credit Card', orderStatus: 'Completed', deliveryType: 'Store Pickup', storeId: 'ST-016', storeLocation: 'Kolkata', salespersonId: 'EMP-6698', employeeName: 'Ashmi Jain' },
  { transactionId: 9, date: '2023-06-16', customerId: 'CUST-43872', customerName: 'Suresh Sharma', phoneNumber: '9317845892', gender: 'Male', age: 35, customerRegion: 'South', customerType: 'New', productId: 'PROD-7475', productName: 'Bluetooth Speaker', brand: 'CyberCore', productCategory: 'Electronics', tags: ['smart', 'portable', 'wireless'], quantity: 3, pricePerUnit: 2720, discountPercentage: 45, totalAmount: 8160, finalAmount: 4488.0, paymentMethod: 'Cash', orderStatus: 'Returned', deliveryType: 'Express', storeId: 'ST-032', storeLocation: 'Jaipur', salespersonId: 'EMP-7244', employeeName: 'Deepak Goyal' },
  { transactionId: 10, date: '2022-07-17', customerId: 'CUST-66880', customerName: 'Ritika Joshi', phoneNumber: '9642689633', gender: 'Female', age: 47, customerRegion: 'North', customerType: 'Loyal', productId: 'PROD-2390', productName: 'Casual Kurta', brand: 'StreetLayer', productCategory: 'Clothing', tags: ['casual', 'fashion'], quantity: 5, pricePerUnit: 1787, discountPercentage: 30, totalAmount: 8935, finalAmount: 6254.5, paymentMethod: 'Cash', orderStatus: 'Returned', deliveryType: 'Express', storeId: 'ST-035', storeLocation: 'Mumbai', salespersonId: 'EMP-6938', employeeName: 'Yash Balyan' },
  { transactionId: 11, date: '2023-03-18', customerId: 'CUST-64912', customerName: 'Sanjay Bansal', phoneNumber: '9268904111', gender: 'Female', age: 57, customerRegion: 'West', customerType: 'New', productId: 'PROD-7692', productName: 'Matte Lipstick', brand: 'VelvetTouch', productCategory: 'Beauty', tags: ['organic', 'skincare'], quantity: 1, pricePerUnit: 4707, discountPercentage: 2, totalAmount: 4707, finalAmount: 4612.86, paymentMethod: 'Credit Card', orderStatus: 'Cancelled', deliveryType: 'Store Pickup', storeId: 'ST-002', storeLocation: 'Jaipur', salespersonId: 'EMP-5075', employeeName: 'Ram Chaudhry' },
  { transactionId: 12, date: '2022-06-10', customerId: 'CUST-58160', customerName: 'Mahesh Mehta', phoneNumber: '9266063747', gender: 'Female', age: 53, customerRegion: 'West', customerType: 'New', productId: 'PROD-3174', productName: 'Wireless Headphones', brand: 'NovaGear', productCategory: 'Electronics', tags: ['smart', 'portable', 'accessories'], quantity: 3, pricePerUnit: 2749, discountPercentage: 21, totalAmount: 8247, finalAmount: 6515.13, paymentMethod: 'Wallet', orderStatus: 'Completed', deliveryType: 'Express', storeId: 'ST-008', storeLocation: 'Bengaluru', salespersonId: 'EMP-4049', employeeName: 'Ram Chaudhry' },
  { transactionId: 13, date: '2023-09-17', customerId: 'CUST-26938', customerName: 'Farhan Khan', phoneNumber: '9491736503', gender: 'Male', age: 40, customerRegion: 'Central', customerType: 'Loyal', productId: 'PROD-8823', productName: 'Bluetooth Speaker', brand: 'TechPulse', productCategory: 'Electronics', tags: ['portable', 'gadgets', 'accessories'], quantity: 5, pricePerUnit: 1223, discountPercentage: 9, totalAmount: 6115, finalAmount: 5564.65, paymentMethod: 'Wallet', orderStatus: 'Completed', deliveryType: 'Standard', storeId: 'ST-042', storeLocation: 'Bengaluru', salespersonId: 'EMP-7771', employeeName: 'Yash Balyan' },
  { transactionId: 14, date: '2021-07-18', customerId: 'CUST-23645', customerName: 'Prerna Chopra', phoneNumber: '9387515030', gender: 'Male', age: 24, customerRegion: 'West', customerType: 'New', productId: 'PROD-6571', productName: 'Bluetooth Speaker', brand: 'VoltEdge', productCategory: 'Electronics', tags: ['accessories', 'wireless'], quantity: 1, pricePerUnit: 2601, discountPercentage: 13, totalAmount: 2601, finalAmount: 2262.87, paymentMethod: 'UPI', orderStatus: 'Pending', deliveryType: 'Store Pickup', storeId: 'ST-024', storeLocation: 'Bengaluru', salespersonId: 'EMP-9226', employeeName: 'Harsh Agarwal' },
  { transactionId: 15, date: '2023-01-15', customerId: 'CUST-56533', customerName: 'Anjali Agarwal', phoneNumber: '9069392523', gender: 'Female', age: 54, customerRegion: 'West', customerType: 'Loyal', productId: 'PROD-7533', productName: 'Bluetooth Speaker', brand: 'VoltEdge', productCategory: 'Electronics', tags: ['gadgets', 'accessories'], quantity: 5, pricePerUnit: 4779, discountPercentage: 48, totalAmount: 23895, finalAmount: 12425.4, paymentMethod: 'Credit Card', orderStatus: 'Pending', deliveryType: 'Store Pickup', storeId: 'ST-038', storeLocation: 'Ahmedabad', salespersonId: 'EMP-5387', employeeName: 'Khushi Agarwal' },
  { transactionId: 16, date: '2023-08-23', customerId: 'CUST-39007', customerName: 'Amit Sharma', phoneNumber: '9755276289', gender: 'Female', age: 35, customerRegion: 'South', customerType: 'Returning', productId: 'PROD-3386', productName: 'Bluetooth Speaker', brand: 'TechPulse', productCategory: 'Electronics', tags: ['gadgets', 'wireless', 'smart'], quantity: 3, pricePerUnit: 861, discountPercentage: 50, totalAmount: 2583, finalAmount: 1291.5, paymentMethod: 'Net Banking', orderStatus: 'Pending', deliveryType: 'Store Pickup', storeId: 'ST-008', storeLocation: 'Mumbai', salespersonId: 'EMP-7505', employeeName: 'Kulasekhar Busi' },
  { transactionId: 17, date: '2022-01-22', customerId: 'CUST-58667', customerName: 'Anjali Reddy', phoneNumber: '9531431835', gender: 'Male', age: 21, customerRegion: 'East', customerType: 'Loyal', productId: 'PROD-4773', productName: 'Wireless Headphones', brand: 'VoltEdge', productCategory: 'Electronics', tags: ['accessories', 'gadgets', 'wireless'], quantity: 5, pricePerUnit: 4376, discountPercentage: 16, totalAmount: 21880, finalAmount: 18379.2, paymentMethod: 'Net Banking', orderStatus: 'Returned', deliveryType: 'Store Pickup', storeId: 'ST-027', storeLocation: 'Pune', salespersonId: 'EMP-7451', employeeName: 'Yash Balyan' },
  { transactionId: 18, date: '2023-09-19', customerId: 'CUST-28378', customerName: 'Kabir Yadav', phoneNumber: '9226175916', gender: 'Female', age: 59, customerRegion: 'South', customerType: 'Loyal', productId: 'PROD-7079', productName: 'Gaming Mouse', brand: 'TechPulse', productCategory: 'Electronics', tags: ['smart', 'gadgets'], quantity: 2, pricePerUnit: 3091, discountPercentage: 34, totalAmount: 6182, finalAmount: 4080.12, paymentMethod: 'Credit Card', orderStatus: 'Completed', deliveryType: 'Standard', storeId: 'ST-024', storeLocation: 'Jaipur', salespersonId: 'EMP-7992', employeeName: 'Harsh Agarwal' },
  { transactionId: 19, date: '2021-09-05', customerId: 'CUST-81808', customerName: 'Farhan Gupta', phoneNumber: '9453873516', gender: 'Female', age: 55, customerRegion: 'North', customerType: 'New', productId: 'PROD-5761', productName: 'Hooded Sweatshirt', brand: 'UrbanWeave', productCategory: 'Clothing', tags: ['cotton', 'formal'], quantity: 4, pricePerUnit: 320, discountPercentage: 2, totalAmount: 1280, finalAmount: 1254.4, paymentMethod: 'Net Banking', orderStatus: 'Pending', deliveryType: 'Store Pickup', storeId: 'ST-044', storeLocation: 'Jaipur', salespersonId: 'EMP-8533', employeeName: 'Kulasekhar Busi' },
  { transactionId: 20, date: '2021-07-14', customerId: 'CUST-40371', customerName: 'Aisha Gupta', phoneNumber: '9713033777', gender: 'Male', age: 50, customerRegion: 'West', customerType: 'Returning', productId: 'PROD-9556', productName: 'Formal Shirt', brand: 'UrbanWeave', productCategory: 'Clothing', tags: ['fashion', 'unisex', 'casual', 'cotton'], quantity: 4, pricePerUnit: 2416, discountPercentage: 30, totalAmount: 9664, finalAmount: 6764.8, paymentMethod: 'Net Banking', orderStatus: 'Completed', deliveryType: 'Store Pickup', storeId: 'ST-009', storeLocation: 'Delhi', salespersonId: 'EMP-5986', employeeName: 'Khushi Agarwal' },
  { transactionId: 21, date: '2021-06-23', customerId: 'CUST-38431', customerName: 'Rahul Verma', phoneNumber: '9070345219', gender: 'Male', age: 49, customerRegion: 'West', customerType: 'New', productId: 'PROD-7348', productName: 'Aloe Vera Gel', brand: 'PureBloom', productCategory: 'Beauty', tags: ['beauty', 'fragrance-free', 'organic'], quantity: 5, pricePerUnit: 4642, discountPercentage: 31, totalAmount: 23210, finalAmount: 16014.9, paymentMethod: 'Wallet', orderStatus: 'Cancelled', deliveryType: 'Standard', storeId: 'ST-028', storeLocation: 'Kolkata', salespersonId: 'EMP-2843', employeeName: 'Khushi Agarwal' },
  { transactionId: 22, date: '2023-02-13', customerId: 'CUST-69462', customerName: 'Amit Verma', phoneNumber: '9995406597', gender: 'Male', age: 47, customerRegion: 'West', customerType: 'New', productId: 'PROD-4354', productName: 'Casual Kurta', brand: 'EliteWear', productCategory: 'Clothing', tags: ['fashion', 'cotton', 'casual'], quantity: 2, pricePerUnit: 2760, discountPercentage: 2, totalAmount: 5520, finalAmount: 5409.6, paymentMethod: 'Wallet', orderStatus: 'Completed', deliveryType: 'Standard', storeId: 'ST-031', storeLocation: 'Lucknow', salespersonId: 'EMP-8280', employeeName: 'Harsh Agarwal' },
  { transactionId: 23, date: '2022-10-20', customerId: 'CUST-52509', customerName: 'Pooja Singh', phoneNumber: '9446447120', gender: 'Female', age: 43, customerRegion: 'West', customerType: 'Returning', productId: 'PROD-3744', productName: 'Matte Lipstick', brand: 'VelvetTouch', productCategory: 'Beauty', tags: ['skincare', 'makeup'], quantity: 4, pricePerUnit: 3966, discountPercentage: 8, totalAmount: 15864, finalAmount: 14594.88, paymentMethod: 'Credit Card', orderStatus: 'Cancelled', deliveryType: 'Express', storeId: 'ST-038', storeLocation: 'Kolkata', salespersonId: 'EMP-7658', employeeName: 'Harsh Agarwal' },
  { transactionId: 24, date: '2023-04-30', customerId: 'CUST-22154', customerName: 'Karan Gupta', phoneNumber: '9820647875', gender: 'Female', age: 43, customerRegion: 'East', customerType: 'Returning', productId: 'PROD-6544', productName: 'Formal Shirt', brand: 'StreetLayer', productCategory: 'Clothing', tags: ['unisex', 'fashion', 'cotton'], quantity: 2, pricePerUnit: 2266, discountPercentage: 31, totalAmount: 4532, finalAmount: 3127.08, paymentMethod: 'Credit Card', orderStatus: 'Pending', deliveryType: 'Store Pickup', storeId: 'ST-049', storeLocation: 'Delhi', salespersonId: 'EMP-2535', employeeName: 'Deepak Goyal' },
  { transactionId: 25, date: '2023-08-30', customerId: 'CUST-10587', customerName: 'Ritika Bansal', phoneNumber: '9856130616', gender: 'Male', age: 28, customerRegion: 'South', customerType: 'New', productId: 'PROD-5173', productName: 'Slim Fit Jeans', brand: 'UrbanWeave', productCategory: 'Clothing', tags: ['fashion', 'cotton', 'formal'], quantity: 4, pricePerUnit: 1951, discountPercentage: 11, totalAmount: 7804, finalAmount: 6945.56, paymentMethod: 'Credit Card', orderStatus: 'Pending', deliveryType: 'Express', storeId: 'ST-041', storeLocation: 'Mumbai', salespersonId: 'EMP-4939', employeeName: 'Harsh Agarwal' },
  { transactionId: 26, date: '2023-05-29', customerId: 'CUST-73216', customerName: 'Kabir Mehta', phoneNumber: '9605702667', gender: 'Female', age: 40, customerRegion: 'East', customerType: 'Returning', productId: 'PROD-4535', productName: 'Smartwatch', brand: 'NovaGear', productCategory: 'Electronics', tags: ['wireless', 'gadgets', 'portable', 'smart'], quantity: 4, pricePerUnit: 1063, discountPercentage: 21, totalAmount: 4252, finalAmount: 3359.08, paymentMethod: 'Net Banking', orderStatus: 'Cancelled', deliveryType: 'Store Pickup', storeId: 'ST-002', storeLocation: 'Ahmedabad', salespersonId: 'EMP-8520', employeeName: 'Kulasekhar Busi' },
  { transactionId: 27, date: '2023-04-07', customerId: 'CUST-34297', customerName: 'Mahesh Reddy', phoneNumber: '9399734065', gender: 'Female', age: 31, customerRegion: 'West', customerType: 'Loyal', productId: 'PROD-2257', productName: 'Cotton T-Shirt', brand: 'UrbanWeave', productCategory: 'Clothing', tags: ['unisex', 'casual', 'cotton'], quantity: 3, pricePerUnit: 1514, discountPercentage: 0, totalAmount: 4542, finalAmount: 4542.0, paymentMethod: 'Wallet', orderStatus: 'Pending', deliveryType: 'Store Pickup', storeId: 'ST-012', storeLocation: 'Chennai', salespersonId: 'EMP-3794', employeeName: 'Ashmi Jain' },
  { transactionId: 28, date: '2021-11-30', customerId: 'CUST-99205', customerName: 'Alisha Bansal', phoneNumber: '9380092674', gender: 'Male', age: 37, customerRegion: 'East', customerType: 'Returning', productId: 'PROD-7683', productName: 'Herbal Face Wash', brand: 'SilkSkin', productCategory: 'Beauty', tags: ['organic', 'beauty', 'makeup'], quantity: 1, pricePerUnit: 3369, discountPercentage: 28, totalAmount: 3369, finalAmount: 2425.68, paymentMethod: 'Cash', orderStatus: 'Cancelled', deliveryType: 'Store Pickup', storeId: 'ST-033', storeLocation: 'Ahmedabad', salespersonId: 'EMP-4761', employeeName: 'Ankit Tiwari' },
  { transactionId: 29, date: '2021-03-25', customerId: 'CUST-46465', customerName: 'Kabir Reddy', phoneNumber: '9511318801', gender: 'Female', age: 42, customerRegion: 'West', customerType: 'New', productId: 'PROD-5032', productName: 'Slim Fit Jeans', brand: 'ComfortLine', productCategory: 'Clothing', tags: ['formal', 'cotton', 'fashion', 'unisex'], quantity: 3, pricePerUnit: 305, discountPercentage: 24, totalAmount: 915, finalAmount: 695.4, paymentMethod: 'Debit Card', orderStatus: 'Cancelled', deliveryType: 'Express', storeId: 'ST-015', storeLocation: 'Ahmedabad', salespersonId: 'EMP-9559', employeeName: 'Ankit Tiwari' },
  { transactionId: 30, date: '2022-04-11', customerId: 'CUST-25581', customerName: 'Zoya Sharma', phoneNumber: '9580565789', gender: 'Male', age: 53, customerRegion: 'Central', customerType: 'New', productId: 'PROD-8510', productName: 'Matte Lipstick', brand: 'PureBloom', productCategory: 'Beauty', tags: ['skincare', 'fragrance-free', 'organic'], quantity: 2, pricePerUnit: 4071, discountPercentage: 1, totalAmount: 8142, finalAmount: 8060.58, paymentMethod: 'Cash', orderStatus: 'Returned', deliveryType: 'Standard', storeId: 'ST-003', storeLocation: 'Jaipur', salespersonId: 'EMP-2061', employeeName: 'Ashmi Jain' },
  { transactionId: 31, date: '2022-05-13', customerId: 'CUST-60519', customerName: 'Divya Singh', phoneNumber: '9154800180', gender: 'Female', age: 27, customerRegion: 'East', customerType: 'New', productId: 'PROD-7925', productName: 'Herbal Face Wash', brand: 'VelvetTouch', productCategory: 'Beauty', tags: ['fragrance-free', 'beauty', 'makeup', 'organic'], quantity: 1, pricePerUnit: 2737, discountPercentage: 20, totalAmount: 2737, finalAmount: 2189.6, paymentMethod: 'Cash', orderStatus: 'Cancelled', deliveryType: 'Express', storeId: 'ST-012', storeLocation: 'Kolkata', salespersonId: 'EMP-4575', employeeName: 'Harsh Agarwal' },
  { transactionId: 32, date: '2021-04-17', customerId: 'CUST-21198', customerName: 'Vivek Patel', phoneNumber: '9430751743', gender: 'Male', age: 59, customerRegion: 'North', customerType: 'New', productId: 'PROD-6272', productName: 'Bluetooth Speaker', brand: 'NovaGear', productCategory: 'Electronics', tags: ['portable', 'accessories'], quantity: 2, pricePerUnit: 2258, discountPercentage: 25, totalAmount: 4516, finalAmount: 3387.0, paymentMethod: 'Wallet', orderStatus: 'Cancelled', deliveryType: 'Store Pickup', storeId: 'ST-029', storeLocation: 'Pune', salespersonId: 'EMP-4224', employeeName: 'Deepak Goyal' },
  { transactionId: 33, date: '2022-01-05', customerId: 'CUST-85127', customerName: 'Zoya Bansal', phoneNumber: '9623509125', gender: 'Female', age: 26, customerRegion: 'South', customerType: 'Returning', productId: 'PROD-8669', productName: 'Matte Lipstick', brand: 'VelvetTouch', productCategory: 'Beauty', tags: ['makeup', 'beauty'], quantity: 3, pricePerUnit: 2001, discountPercentage: 30, totalAmount: 6003, finalAmount: 4202.1, paymentMethod: 'Credit Card', orderStatus: 'Completed', deliveryType: 'Express', storeId: 'ST-019', storeLocation: 'Chennai', salespersonId: 'EMP-8076', employeeName: 'Ashmi Jain' },
  { transactionId: 34, date: '2022-08-12', customerId: 'CUST-30412', customerName: 'Mahesh Iyer', phoneNumber: '9116238258', gender: 'Male', age: 48, customerRegion: 'West', customerType: 'Loyal', productId: 'PROD-5466', productName: 'Skin Repair Serum', brand: 'GlowEssence', productCategory: 'Beauty', tags: ['fragrance-free', 'beauty'], quantity: 3, pricePerUnit: 1428, discountPercentage: 20, totalAmount: 4284, finalAmount: 3427.2, paymentMethod: 'Net Banking', orderStatus: 'Returned', deliveryType: 'Standard', storeId: 'ST-020', storeLocation: 'Kolkata', salespersonId: 'EMP-1390', employeeName: 'Deepak Goyal' },
  { transactionId: 35, date: '2021-10-08', customerId: 'CUST-71052', customerName: 'Anjali Sharma', phoneNumber: '9904078084', gender: 'Female', age: 23, customerRegion: 'East', customerType: 'Returning', productId: 'PROD-9137', productName: 'Hydrating Face Cream', brand: 'VelvetTouch', productCategory: 'Beauty', tags: ['fragrance-free', 'skincare'], quantity: 1, pricePerUnit: 2419, discountPercentage: 35, totalAmount: 2419, finalAmount: 1572.35, paymentMethod: 'Credit Card', orderStatus: 'Returned', deliveryType: 'Store Pickup', storeId: 'ST-033', storeLocation: 'Lucknow', salespersonId: 'EMP-1545', employeeName: 'Deepak Goyal' },
  { transactionId: 36, date: '2022-01-16', customerId: 'CUST-10009', customerName: 'Ritika Verma', phoneNumber: '9861415761', gender: 'Male', age: 25, customerRegion: 'West', customerType: 'Loyal', productId: 'PROD-5418', productName: 'Matte Lipstick', brand: 'GlowEssence', productCategory: 'Beauty', tags: ['makeup', 'fragrance-free'], quantity: 1, pricePerUnit: 338, discountPercentage: 29, totalAmount: 338, finalAmount: 239.98, paymentMethod: 'UPI', orderStatus: 'Returned', deliveryType: 'Store Pickup', storeId: 'ST-014', storeLocation: 'Mumbai', salespersonId: 'EMP-4673', employeeName: 'Harsh Agarwal' },
  { transactionId: 37, date: '2022-05-22', customerId: 'CUST-32738', customerName: 'Ritika Joshi', phoneNumber: '9467843562', gender: 'Male', age: 44, customerRegion: 'Central', customerType: 'New', productId: 'PROD-5816', productName: 'USB-C Charger', brand: 'CyberCore', productCategory: 'Electronics', tags: ['portable', 'wireless', 'accessories', 'gadgets'], quantity: 3, pricePerUnit: 2410, discountPercentage: 22, totalAmount: 7230, finalAmount: 5639.4, paymentMethod: 'Debit Card', orderStatus: 'Returned', deliveryType: 'Store Pickup', storeId: 'ST-049', storeLocation: 'Pune', salespersonId: 'EMP-2452', employeeName: 'Khushi Agarwal' },
  { transactionId: 38, date: '2023-05-09', customerId: 'CUST-32974', customerName: 'Divya Bansal', phoneNumber: '9845860828', gender: 'Female', age: 42, customerRegion: 'North', customerType: 'New', productId: 'PROD-3210', productName: 'Slim Fit Jeans', brand: 'EliteWear', productCategory: 'Clothing', tags: ['unisex', 'casual', 'fashion', 'cotton'], quantity: 1, pricePerUnit: 4733, discountPercentage: 36, totalAmount: 4733, finalAmount: 3029.12, paymentMethod: 'Debit Card', orderStatus: 'Completed', deliveryType: 'Express', storeId: 'ST-037', storeLocation: 'Mumbai', salespersonId: 'EMP-4951', employeeName: 'Deepak Goyal' },
  { transactionId: 39, date: '2022-09-23', customerId: 'CUST-96540', customerName: 'Zoya Sharma', phoneNumber: '9501817103', gender: 'Male', age: 51, customerRegion: 'East', customerType: 'New', productId: 'PROD-1745', productName: 'Hooded Sweatshirt', brand: 'ComfortLine', productCategory: 'Clothing', tags: ['unisex', 'cotton', 'formal'], quantity: 1, pricePerUnit: 3889, discountPercentage: 0, totalAmount: 3889, finalAmount: 3889.0, paymentMethod: 'UPI', orderStatus: 'Pending', deliveryType: 'Express', storeId: 'ST-001', storeLocation: 'Chennai', salespersonId: 'EMP-6180', employeeName: 'Khushi Agarwal' },
  { transactionId: 40, date: '2023-01-05', customerId: 'CUST-99318', customerName: 'Ritika Patel', phoneNumber: '9215033306', gender: 'Male', age: 60, customerRegion: 'Central', customerType: 'Loyal', productId: 'PROD-7140', productName: 'Cotton T-Shirt', brand: 'EliteWear', productCategory: 'Clothing', tags: ['casual', 'unisex', 'fashion', 'formal'], quantity: 5, pricePerUnit: 4542, discountPercentage: 6, totalAmount: 22710, finalAmount: 21347.4, paymentMethod: 'Credit Card', orderStatus: 'Pending', deliveryType: 'Store Pickup', storeId: 'ST-047', storeLocation: 'Hyderabad', salespersonId: 'EMP-2059', employeeName: 'Khushi Agarwal' },
  { transactionId: 41, date: '2022-02-27', customerId: 'CUST-70298', customerName: 'Rahul Reddy', phoneNumber: '9395912178', gender: 'Male', age: 56, customerRegion: 'West', customerType: 'Returning', productId: 'PROD-7359', productName: 'Slim Fit Jeans', brand: 'ComfortLine', productCategory: 'Clothing', tags: ['casual', 'cotton'], quantity: 4, pricePerUnit: 3984, discountPercentage: 24, totalAmount: 15936, finalAmount: 12111.36, paymentMethod: 'Credit Card', orderStatus: 'Completed', deliveryType: 'Express', storeId: 'ST-041', storeLocation: 'Mumbai', salespersonId: 'EMP-1775', employeeName: 'Kulasekhar Busi' },
  { transactionId: 42, date: '2022-07-10', customerId: 'CUST-81320', customerName: 'Rahul Nair', phoneNumber: '9813309379', gender: 'Female', age: 42, customerRegion: 'West', customerType: 'Loyal', productId: 'PROD-4571', productName: 'Smartwatch', brand: 'NovaGear', productCategory: 'Electronics', tags: ['accessories', 'wireless', 'smart'], quantity: 4, pricePerUnit: 4077, discountPercentage: 4, totalAmount: 16308, finalAmount: 15655.68, paymentMethod: 'Debit Card', orderStatus: 'Pending', deliveryType: 'Store Pickup', storeId: 'ST-013', storeLocation: 'Kolkata', salespersonId: 'EMP-2703', employeeName: 'Deepak Goyal' },
  { transactionId: 43, date: '2023-01-31', customerId: 'CUST-82389', customerName: 'Alisha Agarwal', phoneNumber: '9235303933', gender: 'Male', age: 27, customerRegion: 'South', customerType: 'Loyal', productId: 'PROD-7406', productName: 'Gaming Mouse', brand: 'NovaGear', productCategory: 'Electronics', tags: ['gadgets', 'accessories', 'portable'], quantity: 3, pricePerUnit: 2454, discountPercentage: 10, totalAmount: 7362, finalAmount: 6625.8, paymentMethod: 'Debit Card', orderStatus: 'Returned', deliveryType: 'Standard', storeId: 'ST-017', storeLocation: 'Delhi', salespersonId: 'EMP-7383', employeeName: 'Kulasekhar Busi' },
  { transactionId: 44, date: '2021-10-05', customerId: 'CUST-69171', customerName: 'Arjun Verma', phoneNumber: '9061377739', gender: 'Female', age: 26, customerRegion: 'East', customerType: 'New', productId: 'PROD-2255', productName: 'Casual Kurta', brand: 'UrbanWeave', productCategory: 'Clothing', tags: ['unisex', 'fashion'], quantity: 3, pricePerUnit: 4702, discountPercentage: 34, totalAmount: 14106, finalAmount: 9309.96, paymentMethod: 'Cash', orderStatus: 'Completed', deliveryType: 'Standard', storeId: 'ST-021', storeLocation: 'Bengaluru', salespersonId: 'EMP-2772', employeeName: 'Ram Chaudhry' },
  { transactionId: 45, date: '2021-11-23', customerId: 'CUST-49004', customerName: 'Nisha Iyer', phoneNumber: '9931820859', gender: 'Male', age: 52, customerRegion: 'South', customerType: 'Returning', productId: 'PROD-2579', productName: 'Formal Shirt', brand: 'UrbanWeave', productCategory: 'Clothing', tags: ['unisex', 'casual', 'formal', 'fashion'], quantity: 5, pricePerUnit: 2528, discountPercentage: 11, totalAmount: 12640, finalAmount: 11249.6, paymentMethod: 'Cash', orderStatus: 'Cancelled', deliveryType: 'Express', storeId: 'ST-021', storeLocation: 'Jaipur', salespersonId: 'EMP-7051', employeeName: 'Kulasekhar Busi' },
  { transactionId: 46, date: '2022-03-26', customerId: 'CUST-92264', customerName: 'Aisha Iyer', phoneNumber: '9724653947', gender: 'Female', age: 31, customerRegion: 'Central', customerType: 'New', productId: 'PROD-1775', productName: 'Gaming Mouse', brand: 'NovaGear', productCategory: 'Electronics', tags: ['gadgets', 'accessories', 'smart', 'wireless'], quantity: 2, pricePerUnit: 248, discountPercentage: 24, totalAmount: 496, finalAmount: 376.96, paymentMethod: 'UPI', orderStatus: 'Pending', deliveryType: 'Store Pickup', storeId: 'ST-019', storeLocation: 'Pune', salespersonId: 'EMP-4284', employeeName: 'Khushi Agarwal' },
  { transactionId: 47, date: '2022-06-17', customerId: 'CUST-71546', customerName: 'Anjali Agarwal', phoneNumber: '9575934556', gender: 'Female', age: 57, customerRegion: 'South', customerType: 'Loyal', productId: 'PROD-7195', productName: 'Gaming Mouse', brand: 'NovaGear', productCategory: 'Electronics', tags: ['accessories', 'gadgets', 'smart', 'wireless'], quantity: 2, pricePerUnit: 1679, discountPercentage: 14, totalAmount: 3358, finalAmount: 2887.88, paymentMethod: 'UPI', orderStatus: 'Cancelled', deliveryType: 'Standard', storeId: 'ST-010', storeLocation: 'Jaipur', salespersonId: 'EMP-5276', employeeName: 'Kulasekhar Busi' },
  { transactionId: 48, date: '2023-06-10', customerId: 'CUST-56241', customerName: 'Vivek Chopra', phoneNumber: '9022368293', gender: 'Male', age: 56, customerRegion: 'North', customerType: 'Loyal', productId: 'PROD-7136', productName: 'Skin Repair Serum', brand: 'VelvetTouch', productCategory: 'Beauty', tags: ['skincare', 'makeup'], quantity: 2, pricePerUnit: 3431, discountPercentage: 14, totalAmount: 6862, finalAmount: 5901.32, paymentMethod: 'Net Banking', orderStatus: 'Returned', deliveryType: 'Express', storeId: 'ST-010', storeLocation: 'Mumbai', salespersonId: 'EMP-5101', employeeName: 'Harsh Agarwal' },
  { transactionId: 49, date: '2021-03-04', customerId: 'CUST-80966', customerName: 'Alisha Yadav', phoneNumber: '9364835973', gender: 'Male', age: 31, customerRegion: 'North', customerType: 'New', productId: 'PROD-9309', productName: 'Cotton T-Shirt', brand: 'StreetLayer', productCategory: 'Clothing', tags: ['formal', 'casual', 'unisex'], quantity: 4, pricePerUnit: 3248, discountPercentage: 31, totalAmount: 12992, finalAmount: 8964.48, paymentMethod: 'Wallet', orderStatus: 'Cancelled', deliveryType: 'Store Pickup', storeId: 'ST-035', storeLocation: 'Mumbai', salespersonId: 'EMP-9813', employeeName: 'Ankit Tiwari' },
  { transactionId: 50, date: '2022-01-07', customerId: 'CUST-66475', customerName: 'Kabir Das', phoneNumber: '9405971426', gender: 'Female', age: 21, customerRegion: 'Central', customerType: 'Loyal', productId: 'PROD-6315', productName: 'Aloe Vera Gel', brand: 'PureBloom', productCategory: 'Beauty', tags: ['makeup', 'skincare', 'beauty', 'organic'], quantity: 4, pricePerUnit: 3056, discountPercentage: 5, totalAmount: 12224, finalAmount: 11612.8, paymentMethod: 'Credit Card', orderStatus: 'Pending', deliveryType: 'Standard', storeId: 'ST-021', storeLocation: 'Kolkata', salespersonId: 'EMP-8523', employeeName: 'Deepak Goyal' },
];

async function main() {
  console.log('🌱 Starting database seed...');
  console.log('📊 Seeding 50 sales transactions (hardcoded data)');

  // Clear existing data
  console.log('🗑️  Clearing existing sales transactions...');
  await prisma.salesTransaction.deleteMany({});

  // Insert all data at once
  console.log('⏳ Inserting 50 records into database...');
  
  await prisma.salesTransaction.createMany({
    data: salesData,
    skipDuplicates: true,
  });

  console.log('✅ All records inserted successfully!');
  
  // Verify count
  const count = await prisma.salesTransaction.count();
  console.log(`📈 Total records in database: ${count}`);
  
  if (count === 50) {
    console.log('✨ Seed completed successfully! Database ready for use.');
  } else {
    console.warn(`⚠️  Warning: Expected 50 records but found ${count}`);
  }
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
